### ISSUE TITLE
Strange type errors compiling on stackage nightly

### ISSUE THREAD

**Issue by DanBurton** [nakaji-dayo/yesod-job-queue#10] opened 2016-11-23 05:43 UTC
How to reproduce:

```bash
$ stack unpack yesod-job-queue-0.3.0.1
$ cd yesod-job-queue-0.3.0.1/
<< add custom stack.yaml >>
$ stack build
```

```yaml
# stack.yaml
resolver: nightly-2016-11-22
extra-deps:
- api-field-json-th-0.1.0.1
- cron-0.4.2
```

This gives some really strange, long type errors.

```
[4 of 5] Compiling Yesod.JobQueue   ( Yesod/JobQueue.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Yesod/JobQueue.o )

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:74:3: error:
    • Couldn't match type ‘forall a.
                           Data.Aeson.Encoding.Internal.Encoding' a’
                     with ‘Data.Aeson.Encoding.Internal.Encoding' a0’
      Expected type: [Data.Aeson.Encoding.Internal.Encoding' a0]
        Actual type: [forall a. Data.Aeson.Encoding.Internal.Encoding' a]
    • In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.wrapObject’, namely
        ‘Data.Aeson.Encoding.Internal.econcat
           (L.intersperse
              Data.Aeson.Encoding.Internal.comma
              [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
               ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
               ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
               ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))])’
      In the expression:
        Data.Aeson.Encoding.Internal.wrapObject
          (Data.Aeson.Encoding.Internal.econcat
             (L.intersperse
                Data.Aeson.Encoding.Internal.comma
                [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
                 ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
                 ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
                 ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]))

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:74:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:74:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:74:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:74:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:74:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:74:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:74:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:74:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "jobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_asSg))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "threadId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_asSh))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "jobId"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg3_asSi))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "startTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg4_asSj)))]’

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:87:3: error:
    • Couldn't match type ‘forall a.
                           Data.Aeson.Encoding.Internal.Encoding' a’
                     with ‘Data.Aeson.Encoding.Internal.Encoding' a1’
      Expected type: [Data.Aeson.Encoding.Internal.Encoding' a1]
        Actual type: [forall a. Data.Aeson.Encoding.Internal.Encoding' a]
    • In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.wrapObject’, namely
        ‘Data.Aeson.Encoding.Internal.econcat
           (L.intersperse
              Data.Aeson.Encoding.Internal.comma
              [((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
               ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
                Data.Aeson.Encoding.Internal.><
                  (Data.Aeson.Encoding.Internal.colon
                   Data.Aeson.Encoding.Internal.><
                     (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))])’
      In the expression:
        Data.Aeson.Encoding.Internal.wrapObject
          (Data.Aeson.Encoding.Internal.econcat
             (L.intersperse
                Data.Aeson.Encoding.Internal.comma
                [((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
                 ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
                  Data.Aeson.Encoding.Internal.><
                    (Data.Aeson.Encoding.Internal.colon
                     Data.Aeson.Encoding.Internal.><
                       (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]))

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:87:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:87:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]’

/Users/danburton/scratch/yesod-job-queue-0.3.0.1/Yesod/JobQueue.hs:87:3: error:
    • Couldn't match type ‘a’ with ‘Value’
      ‘a’ is a rigid type variable bound by
        a type expected by the context:
          forall a. Data.Aeson.Encoding.Internal.Encoding' a
        at Yesod/JobQueue.hs:87:3
      Expected type: forall a. Data.Aeson.Encoding.Internal.Encoding' a
        Actual type: Data.Aeson.Encoding.Internal.Encoding' Value
    • In the expression:
        ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
         Data.Aeson.Encoding.Internal.><
           (Data.Aeson.Encoding.Internal.colon
            Data.Aeson.Encoding.Internal.><
              (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))
      In the second argument of ‘L.intersperse’, namely
        ‘[((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
          ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
           Data.Aeson.Encoding.Internal.><
             (Data.Aeson.Encoding.Internal.colon
              Data.Aeson.Encoding.Internal.><
                (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]’
      In the first argument of ‘Data.Aeson.Encoding.Internal.econcat’, namely
        ‘L.intersperse
           Data.Aeson.Encoding.Internal.comma
           [((Data.Aeson.Encoding.Internal.text (T.pack "queueJobType"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg1_aujo))),
            ((Data.Aeson.Encoding.Internal.text (T.pack "queueTime"))
             Data.Aeson.Encoding.Internal.><
               (Data.Aeson.Encoding.Internal.colon
                Data.Aeson.Encoding.Internal.><
                  (aeson-1.0.2.1:Data.Aeson.Types.ToJSON.toEncoding arg2_aujp)))]’
```

**Comment by cdepillabout** [comment] 2016-11-24 11:11
This appears to caused by `aeson-1.0.0.0`.  Compiling `yesod-job-queue` with `aeson-0.11.2.1` works fine, but using `aeson-1.0.0.0` (or anything after that) fails.

I'm not sure about the actual cause of this though.  It looks like this error is happening from the expansion of the `deriveToJSON` template haskell statements for `RunningJob`.

**Comment by cdepillabout** [comment] 2017-02-14 11:41
@nakaji-dayo Would it be possible to get `yesod-job-queue` and `api-field-json-th` back into stackage (and ideally into lts-8)?

I am able to successfully compile `yesod-job-queue-0.3.0.1` and `api-field-json-th-0.1.0.1` on lts-8.

However, in looking through the commits for this repo, I don't see the commits for bumping to version 0.3.0.1.  Is there some code that needs to be committed?

**Comment by nakaji-dayo** [comment] 2017-05-27 08:53
@cdepillabout I put yesod-job-queue back into stackage.

I'm sorry. I could not find version 0.3.0.1. I ignored this version and bump version.

**Closed as completed by nakaji-dayo** 2017-05-27 08:53 UTC
